name: Auto-deploy
on:
  push:
    branches:
      - "master"

permissions:
  contents: write
  pages: write
  id-token: write
  
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Run preparation
        run: |
          rm -rf node_modules package-lock.json
          npm i

#      - name: Set ENV variables
#        run: |
#        echo "ENVIRONMENT=production" >> $GITHUB_ENV
#        echo "BUCKET=business.clevergift.com" >> $GITHUB_ENV
#        echo "DISTRIBUTION_ID=EPKDFWYY8WXON" >> $GITHUB_ENV

      - name: Setup GitHub credentials
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
      - name: Build
        run: npm run build

      - name: List dist contents
        run: ls -la ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist